// Run against a local app: BASE_URL=http://127.0.0.1:18894 PLAYWRIGHT_PATH=/path/to/playwright-core/index.mjs node tests/actions_browser_smoke.mjs
const { chromium } = await import(process.env.PLAYWRIGHT_PATH || 'playwright');
import assert from 'node:assert/strict';
const browser = await chromium.launch({ executablePath: '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto(process.env.BASE_URL || 'http://127.0.0.1:8000');
await page.getByRole('button', { name: 'Search actions', exact: true }).waitFor();
await page.evaluate(() => { o_state.o_panel_visibility.stats = false; });
await page.keyboard.press('F3');
await page.getByRole('dialog').waitFor();
await page.getByRole('textbox', { name: 'Search actions', exact: true }).fill('cap');
await page.locator('.action-results button').filter({ hasText: 'Capture Image' }).waitFor();
await page.evaluate(async () => {
    const canvas = document.createElement('canvas'); canvas.width = 16; canvas.height = 16;
    const ctx = canvas.getContext('2d'); ctx.fillStyle = 'red'; ctx.fillRect(0, 0, 16, 16);
    const video = document.querySelector('#webcamVideo'); video.srcObject = canvas.captureStream(10); await video.play();
});
const downloaded = page.waitForEvent('download');
await page.keyboard.press('Enter');
assert.match((await downloaded).suggestedFilename(), /^capture-.*\.png$/);
const shortcutDownload = page.waitForEvent('download');
await page.keyboard.press('Control+Shift+I');
assert.match((await shortcutDownload).suggestedFilename(), /^capture-.*\.png$/);
await page.keyboard.press('F3');
await page.keyboard.press('Escape');
await page.evaluate(() => window.addEventListener('keydown', e => { if(e.ctrlKey && e.key.toLowerCase() === 'f') window.findPrevented = e.defaultPrevented; }));
await page.keyboard.press('Control+f');
await page.getByRole('dialog').waitFor();
assert.equal(await page.evaluate(() => window.findPrevented), true);
await page.keyboard.press('Control+f');
assert.equal(await page.evaluate(() => window.findPrevented), true);
assert.equal(await page.getByRole('textbox', { name: 'Search actions', exact: true }).evaluate(el => document.activeElement === el), true);
await page.getByRole('textbox', { name: 'Search actions', exact: true }).fill('Toggle stats');
await page.keyboard.press('Enter');
assert.equal(await page.locator('.panel-stats.visible').count(), 1);
await page.getByRole('button', { name: 'Search actions', exact: true }).click();
await page.getByLabel('Edit bindings').check();
await page.getByRole('textbox', { name: 'Search actions', exact: true }).fill('Toggle stats');
await page.locator('.action-results button').click();
await page.getByLabel('Record shortcut').press('Control+Shift+Y');
await page.getByRole('button', { name: 'Add binding', exact: true }).click();
await page.getByRole('button', { name: 'Save', exact: true }).click();
assert.match(await page.locator('.action-results kbd').innerText(), /Ctrl/);
await page.getByRole('button', { name: 'Close', exact: true }).click();
await page.keyboard.press('Control+Shift+Y');
assert.equal(await page.locator('.panel-stats.visible').count(), 0);
await page.reload();
await page.getByRole('button', { name: 'Search actions', exact: true }).waitFor();
await page.evaluate(() => { o_state.o_panel_visibility.stats = false; });
await page.keyboard.press('Control+Shift+Y');
assert.equal(await page.locator('.panel-stats.visible').count(), 1);
await page.keyboard.press('F3');
await page.getByRole('dialog').waitFor();
await page.screenshot({ path: '/tmp/omm-actions.png' });
assert.deepEqual(errors, []);
console.log('Palette shortcuts, search, image download, Enter invocation, rebinding, persistence, and rendering passed.');
await browser.close();
